version: '{build}'
branches:
  only:
    - master
    - /^hptsqfix-.*/
image:
  - Visual Studio 2017
environment:
  matrix:
    - generator: Visual Studio 15 2017
      cf: -DBUILD_SHARED_LIBS=OFF
    - generator: Visual Studio 15 2017
      cf: -DBUILD_SHARED_LIBS=ON
    - generator: Visual Studio 15 2017 Win64
      cf: -DBUILD_SHARED_LIBS=OFF
    - generator: Visual Studio 15 2017 Win64
      cf: -DBUILD_SHARED_LIBS=ON
install:
  - cmd: git clone https://github.com/huskyproject/huskylib  C:\projects\huskylib
  - cmd: git clone https://github.com/huskyproject/smapi  C:\projects\smapi
  - cmd: git clone https://github.com/huskyproject/fidoconf  C:\projects\fidoconf
build_script:
  - cmd: 
      cd C:\projects\huskylib && mkdir build && cd build && cmake --version &&  cmake .. -G "%GENERATOR%" "%CF%" && cmake --build . -- /P:Configuration=Release &&
      cd C:\projects\smapi && mkdir build && cd build && cmake --version &&  cmake .. -G "%GENERATOR%" "%CF%" && cmake --build . -- /P:Configuration=Release &&
      cd C:\projects\fidoconf && mkdir build && cd build && cmake --version &&  cmake .. -G "%GENERATOR%" "%CF%" && cmake --build . -- /P:Configuration=Release &&
      cd C:\projects\hptsqfix && mkdir build && cd build && cmake --version &&  cmake .. -G "%GENERATOR%" "%CF%" && cmake --build . -- /P:Configuration=Release
  - if ["%CF%"]==["-DBUILD_SHARED_LIBS=OFF"] (cpack)
artifacts:
  - path: build\*.7z
    name: dist
deploy:
  provider: GitHub
  artifact: dist
  auth_token: $(GITHUB_OAUTH_TOKEN)
  on:
    appveyor_repo_tag: true
