# Microsoft Visual C++ Makefile

CC=     cl
CFLAGS= -nologo -Zp1 -I.. -Ih
CDEFS=  -D__NT__ -DNT -DWINNT -D_CONSOLE
COPT=   -O2
TLIB=   lib -nologo

SMAPIL=	..\smapi\smapimvc.lib

all: hptsqfix.exe

hptsqfix.exe:
        $(CC) $(CFLAGS) $(CDEFS) $(COPT) -Fe$@ src\hptsqfix.c $(SMAPIL)

clean:
	-del *.obj

distclean: clean
	-del src\*.exe
