CC      = wcc386
LINK    = WLINK
SRC     = src

CFLAGS  = -zq -wx -bt=os2v2 -j -ih;.. -oneatx -5 -DOS2
LFLAGS  = system os2v2

OBJS = hptsqfix.obj

all: $(OBJS) hptsqfix.exe

$(OBJS): $(SRC)\*.c
  @echo compiling $*.c
  $(CC) $(CFLAGS) $(SRC)\$*.c

hptsqfix.exe: $(OBJS)
  @echo linking hptsqfix
  $(LINK) $(LFLAGS) FILE hptsqfix.obj Library ..\smapi\smapiwco.lib, ..\fidoconf\fconfwco.lib NAME hptsqfix.exe

clean:
	-DEL *.OBJ
	-DEL *.err
	-DEL hptsqfix.exe

