# $Id$
#
# Microsoft Visual C++ Makefile for build hptsqfix static library

CC	= cl
CFLAGS	= -nologo -Zp1
CINCL	= -I..\h -I..\..\fidoconf -I..\..\smapi -I..\..\huskylib
CDEFS	= -D__NT__ -DNT -DWINNT -D_CONSOLE
COPT	= -O2
TLIB	= lib -nologo

LIBS	= ..\..\huskylib\make\huskymvc.lib ..\..\smapi\make\smapimvc.lib

all: hptsqfix.exe

hptsqfix.exe:
        $(CC) $(CFLAGS) $(CINCL) $(CDEFS) $(COPT) \
	-Fe$@ ..\src\hptsqfix.c $(LIBS)

clean:
	-del *.obj

distclean: clean
	-del *.exe
