CC      = wcc386
LINK    = WLINK
SRC     = ..\src

CFLAGS  = -zq -wx -bt=nt -i..\h;..\.. -oneatx -5
LFLAGS  =

OBJS = hptsqfix.obj

all: $(OBJS) hptsqfix.exe

$(OBJS): $(SRC)\*.c
  @echo compiling $*.c
  $(CC) $(CFLAGS) $(SRC)\$*.c

hptsqfix.exe: $(OBJS)
  @echo linking hptsqfix
  $(LINK) $(LFLAGS) FILE hptsqfix.obj Library ..\..\smapi\smapiwcw, ..\..\fidoconf\fconfwcw.lib NAME hptsqfix.exe

clean:
	-DEL *.OBJ
	-DEL *.err
	-DEL hptsqfix.exe

