
CC=gcc
RM=del

CDEFS =-c -I../h -I../..
CFLAGS=-Wall
COPT  =-O3

LFLAGS=-L../../smapi -L../../fidoconf
LIBS=-lfidoconfigmgw -lsmapimgw -luser32
SRC_DIR=../src/

default: all

TARGET=hptsqfix.exe

OBJS=hptsqfix.o

all: $(TARGET)

%.o: $(SRC_DIR)%.c
	$(CC) $(CFLAGS) $(CDEFS) $(COPT) $(SRC_DIR)$*.c

$(TARGET): $(OBJS)
	$(CC) $(LFLAGS) -o $(TARGET) $(OBJS) $(LIBS)

clean:
	-$(RM) *.o

distclean:
	-$(RM) $(TARGET)
